version: '3'
services:
  php:
    build:
      context: ./php
      args: 
      - TIMEZONE=${TIMEZONE}
      - CHANGE_SOURCE=${CHANGE_SOURCE}
      - PHP_VERSION=${PHP_VERSION}
      - SWOOLE_VERSION=${SWOOLE_VERSION}
      - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    image: lnmp-php
    restart: always
    volumes:
      - ${WWWROOT}:/data/wwwroot
    container_name: compose-php
    networks:
      - lnmp-tier
  nginx:
    build:
      context: ./nginx
      args: 
      - TIMEZONE=${TIMEZONE}
      - CHANGE_SOURCE=${CHANGE_SOURCE}
      - NGINX_VERSION=${NGINX_VERSION}
    image: lnmp-nginx
    restart: always
    depends_on:
      - php
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${WWWROOT}:/data/wwwroot
    container_name: compose-nginx
    networks:
    ports:
      - 80:80
    networks:
      - lnmp-tier

networks:
  lnmp-tier:
    driver: bridge