version: '3'
services:
  php:
    build:
      context: ./php
      args: 
      - TIMEZONE=${TIMEZONE}
      - CHANGE_SOURCE=${CHANGE_SOURCE}
      - PHP_VERSION=${PHP_VERSION}
      - SWOOLE_VERSION=${SWOOLE_VERSION}
      - INSTALL_XDEBUG=${INSTALL_XDEBUG}
      - HIREDIS_VERSION=${HIREDIS_VERSION}
    image: lnmp-php
    restart: always
    volumes:
      - ${WWWROOT}:/data/wwwroot
    container_name: compose-php
    networks:
      - lnmp-tier
  nginx:
    build:
      context: ./nginx
      args: 
      - TIMEZONE=${TIMEZONE}
      - CHANGE_SOURCE=${CHANGE_SOURCE}
      - NGINX_VERSION=${NGINX_VERSION}
    image: lnmp-nginx
    restart: always
    depends_on:
      - php
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${WWWROOT}:/data/wwwroot
    container_name: compose-nginx
    networks:
    ports:
      - 80:80
    networks:
      - lnmp-tier
  mysql:
    build:
      context: ./mysql
      args: 
        - MYSQL_VERSION=${MYSQL_VERSION}
    image: lnmp-mysql
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes: 
      - ${DB_MYSQL_PATH}:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    ports: 
      - ${MYSQL_PORT}:3306

networks:
  lnmp-tier:
    driver: bridge